USE [MegaTravel]
GO

/****** Object:  Table [dbo].[Login]    Script Date: 8/15/2022 4:25:59 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Login](
	[ID] [int] NOT NULL,
	[UserType] [nchar](10) NOT NULL,
	[UserName] [varchar](50) NOT NULL,
	[Password] [varchar](max) NOT NULL,
 CONSTRAINT [PK_Login] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[Login]  WITH NOCHECK ADD  CONSTRAINT [FK_Login_Agent] FOREIGN KEY([ID])
REFERENCES [dbo].[Agent] ([AgentID])
NOT FOR REPLICATION 
GO

ALTER TABLE [dbo].[Login] NOCHECK CONSTRAINT [FK_Login_Agent]
GO

ALTER TABLE [dbo].[Login]  WITH NOCHECK ADD  CONSTRAINT [FK_Login_User] FOREIGN KEY([ID])
REFERENCES [dbo].[Users] ([UserID])
NOT FOR REPLICATION 
GO

ALTER TABLE [dbo].[Login] NOCHECK CONSTRAINT [FK_Login_User]
GO


